#!/bin/bash

## The very first of all my bash scripting journey.
# echo "Hi!"


## Testing a very noob experience with printing numbers.
# echo 1;
# sleep 1;
# echo 2;
# sleep 1;
# echo 3;
# sleep 1;
# echo 4;
# sleep 1;
# echo 5;
# sleep 1;
# 
# echo "......................";
# echo "Done";


